# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc0bbe51461febdb2f7e0617ed6ecae9d96d67289125c2f834b29f017251368ab6673842c2b83b086ef85e2d4a078a6cec15c2b3295261cfb1831b82e9cfc046

test:
  secret_key_base: f78578f1bb3ec18a1db12d9ff7f5ed5887486ad596b921937debba4dc22a291682560a51e1a77607adbfd82e085dfab807c856a10e368cef0dad004bea300292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
